### ISSUE TITLE
PEP-8 Compliance

### ISSUE THREAD

**Issue by akkatracker** [faizann24/XssPy#15]
@faizann24 

I was wondering if you'd like me to make this code PEP-8 (Python style guide: https://www.python.org/dev/peps/pep-0008/) compliant 

Just off the surface this would mean making indents a multiple of 4, putting a space after `#` in inline comments as well as some other small things. 

Shouldn't take long and stylistically should make this code much better.

**Comment by glen-mac** [comment]
I think this would be good - project as it stands has weird indenting.

**Comment by akkatracker** [comment]
Yep, I think I'll make it compliant today, I'll PR when it's ready. If for some reason @faizann24 doesn't want to make it PEP-8 compliant he can close my PR (I can't see any reason for it though)
