### ISSUE TITLE
sintax error

### ISSUE THREAD

**Issue by 3xp10i7** [faizann24/XssPy#2]
can not set up tool what is the problem?
![screenshot from 2016-05-24 11-01-10](https://cloud.githubusercontent.com/assets/19259349/15493652/768f1236-2153-11e6-9c10-335bb79c2c8b.png)

**Comment by faizann24** [comment]
Kindly write 
pip install mechanize

If the installation goes right, run this tool. Let me know if this solves the issue. I forgot to update it on the readme.

**Comment by 3xp10i7** [comment]
it is ok with mechanize
![screenshot from 2016-05-24 13-32-50](https://cloud.githubusercontent.com/assets/19259349/15497367/71a7ee5e-2168-11e6-9558-ea5b695ad840.png)

**Comment by 3xp10i7** [comment]
turns out need to run : python ./xsspy.py
