### ISSUE TITLE
Accept pull requests

### ISSUE THREAD

**Issue by glen-mac** [faizann24/XssPy#8]
I would love to contribute to this project - but it doesn't look like you are accepting pull requests, is there a reason?

**Comment by faizann24** [comment]
Hey glen,

I was really busy. I have just accepted all of them.

Best Regards

**Comment by glen-mac** [comment]
Thanks!

**Comment by glen-mac** [comment]
More to come - please accept

**Comment by faizann24** [comment]
I've accepted all pull requests.

Thanks

**Comment by akkatracker** [comment]
Can we close this :) Thanks @glen-mac for cleaning the code up - much easier to use without every link being logged.

**Comment by glen-mac** [comment]
Thanks!
